[workspace]

members = [
    "aggregator",
    "bin/node",
    "bin/runtime",
    "finality-aleph",
    "pallets/aleph",
    "pallets/elections",
    "pallets/support",
    "primitives",
]

exclude = [
  "aleph-client",
  "bin/cliain",
]
